---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: bento/oracle-7.4

suites:
  - name: dnsclient
    run_list:
      - recipe[segulja_dns::client]
    verifier:
      inspec_tests:
        - test/smoke/default/client_test.rb
    attributes:
  - name: dnsserver
    run_list:
      - recipe[segulja_dns::server]
      - recipe[segulja_dns::client]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
